[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'altercation/vim-colors-solarized'
#hook_add = 'source ~/.vim/plugins/vim-colors-solarized.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.vim/plugins/nerdtree.vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/plugins/lightline.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tsaleh/vim-align'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = 'source ~/.vim/plugins/vim-lsp-settings.vim'

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = 'source ~/.vim/plugins/gruvbox.vim'
