#!/bin/sh

set -e
set -x

BASEBACKUPDIR="${HOME}/.dotfiles.bak"
BACKUPDIR=${BASEBACKUPDIR}/`date +%Y%m%d%H%M%S`
CURRENT=`pwd`
LISTFILE='install_list'

mkbakdir() {
  [ -d ${BASEBACKUPDIR} ] || mkdir ${BASEBACKUPDIR}
  [ -d ${BACKUPDIR} ] || mkdir -p ${BACKUPDIR}
}

backup() {
  local TARGET=$1
  mkbakdir
  local DIRNAME=`dirname ${BACKUPDIR}/$1`
  if [ ${BACKUPDIR} != ${DIRNAME} ]; then
    mkdir -p ${DIRNAME}
  fi
  mv ${HOME}/$1 ${DIRNAME}
  echo ${TARGET}" is backup"
}

exists() {
  local TARGET=$1
  local TYPE=`file -b ${TARGET}`
  if [ "${TYPE}" == "directory" ]; then
    [ -d ${HOME}/${TARGET} ]
  else
    [ -f ${HOME}/${TARGET} ]
  fi
}

# main
while read FILE; do
  echo "===== ${FILE} ====="
  exists ${FILE} && backup ${FILE}
  cp -r ${CURRENT}/${FILE} ${HOME}/${FILE}
  echo ${FILE}" ok"
done < ${LISTFILE}
