#!/bin/bash

CURRENT=`pwd`
LISTFILE='target_list'

exists() {
  local TARGET=$1
  local TYPE=`file -b ${TARGET}`
  if [ "${TYPE}" == "directory" ]; then
    [ -d ${HOME}/${TARGET} ]
  else
    [ -f ${HOME}/${TARGET} ]
  fi
}

# main
echo "##### rcdiff start. #####"
while read FILE; do
  if exists ${FILE}; then
    diff -r ${CURRENT}/${FILE} ${HOME}/${FILE} > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "==== ${FILE} ===="
        diff -r ${CURRENT}/${FILE} ${HOME}/${FILE}
    fi
  fi
done < ${LISTFILE}
echo "##### rcdiff end. #####"
