#!/bin/zsh

CODE=$1

if [[ "all" == "${CODE}" ]]; then
  for code ({000..255}) print -P -- "$code: %F{$code}This is how your text would look like%f"
  exit 0
fi

print -P -- "${CODE}: %F{${CODE}}This is how your text would look like%f"
