#!/bin/bash

echo 'remote login.';

LIST="clear "
if [ -f ~/.ssh/config ]; then
    LIST=${LIST}`cat ~/.ssh/config | grep -E "^Host|^#" | grep -v '*' | awk '{print $2}'`
fi

select MENU in ${LIST}; do
    case "${MENU}" in
        clear ) clear;;
        *     )
            COUNT=`cat ~/.ssh/config | grep -e "^Host ${REPLY}$" | wc -l `
            if [ ${COUNT} -eq 1 ]; then
                TARGET=${REPLY}
            else
                COUNT=`cat ~/.ssh/config | grep -e "^Host ${MENU}$" | wc -l`
                if [ ${COUNT} -ne 1 ]; then
                    echo 'quit.'; exit 0;
                fi

                TARGET=${MENU}
            fi
            ssh ${TARGET};
            ;;
    esac
done
