memodir = "/home/m3y/.ghq/src/github.com/m3y/documents"
editor = "/usr/bin/nvim"
column = 30
width = 0
selectcmd = "peco"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "/home/m3y/.config/memo-plugins"
templatedirfile = ""
templatebodyfile = ""
