memodir = "~/.ghq/src/github.com/m3y/documents"
editor = "${EDITOR}"
column = 30
width = 0
selectcmd = "peco"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "~/.config/memo-plugins"
templatedirfile = ""
templatebodyfile = ""
