- hosts: target
  gather_facts: no
  become: no
  tasks:
    - name: dotfiles のチェックアウト
      git:
        repo=https://github.com/m3y/dotfiles.git
        dest=~/.ghq/github.com/m3y/dotfiles
        accept_hostkey=yes

    - name: tmux 設定の反映
      file:
        src: ~/.ghq/github.com/m3y/dotfiles/.tmux.conf
        dest: ~/.tmux.conf
        state: link
        force: yes

    - name: git 設定の反映
      file:
        src: ~/.ghq/github.com/m3y/dotfiles/{{ item }}
        dest: ~/{{ item }}
        state: link
        force: yes
      with_items:
        - .gitconfig
        - .gitconfig.local
        - .gitignore

    - name: bash 設定の反映
      file:
        src: ~/.ghq/github.com/m3y/dotfiles/{{ item }}
        dest: ~/{{ item }}
        state: link
        force: yes
      with_items:
        - .bashrc
        - .bash_prompt
        - .bash_profile
        - .bash_git_completion

    - name: peco 設定の反映
      file:
        src: ~/.ghq/github.com/m3y/dotfiles/.peco
        dest: ~/.peco
        state: link
        force: yes

    - name: ssh configの反映
      file:
        src: ~/.ghq/github.com/m3y/dotfiles/ssh_config
        dest: ~/.ssh/config
        state: link
        force: yes

    - name: vim 設定の反映
      file:
        src: ~/.ghq/github.com/m3y/dotfiles/{{ item }}
        dest: ~/{{ item }}
        state: link
        force: yes
      with_items:
        - .vimrc
        - .vim

    - name: linux bin 設定
      file:
        src: ~/.ghq/github.com/m3y/dotfiles/.bin
        dest: ~/.bin
        state: link
        force: yes

    - name: etc 用ディレクトリ作成
      file:
        path: ~/.etc
        state: directory
