- hosts: localhost
  connection: local
  gather_facts: yes
  sudo: no
  vars:
    rcdir: "{{ ansible_env.PWD }}/../"
  tasks:
    - name: tmux 設定の反映
      file:
        src: "{{ rcdir }}/.tmux.conf"
        dest: ~/.tmux.conf
        state: link
        force: yes

    - name: git 設定の反映
      file:
        src: "{{ rcdir }}/{{ item }}"
        dest: ~/{{ item }}
        state: link
        force: yes
      with_items:
        - .gitconfig
        - .gitconfig.local
        - .gitignore

    - name: bash 設定の反映
      file:
        src: "{{ rcdir }}/{{ item }}"
        dest: ~/{{ item }}
        state: link
        force: yes
      with_items:
        - .bashrc
        - .bash_prompt
        - .bash_profile
        - .bash_git_completion

    - name: peco 設定の反映
      file:
        src: "{{ rcdir }}/.peco"
        dest: ~/.peco
        state: link
        force: yes

    - name: ssh configの反映
      file:
        src: "{{ rcdir }}/ssh_config"
        dest: ~/.ssh/config
        state: link
        force: yes

    - name: vim 設定の反映
      file:
        src: "{{ rcdir }}/{{ item }}"
        dest: ~/{{ item }}
        state: link
        force: yes
      with_items:
        - .vimrc
        - .vim

    - name: neobundle 設定
      git:
        repo=https://github.com/Shougo/neobundle.vim
        dest=~/.vim/bundle/neobundle.vim
        accept_hostkey=yes

    - name: vim pluginのインストール
      command: ~/.vim/bundle/neobundle.vim/bin/neoinstall

    - name: solarized 設定
      file:
        src: ~/.vim/bundle/vim-colors-solarized/colors/solarized.vim
        dest: ~/.vim/colors/solarized.vim
        state: link
        force: yes

    - name: nerdtree plugin の設定
      copy:
          src: "{{ rcdir }}/grep_menuitem.vim"
          dest: ~/.vim/bundle/nerdtree/nerdtree_plugin/grep_menuitem.vim

    - name: linux bin 設定
      file:
        src: "{{ rcdir }}/.bin"
        dest: ~/.bin
        state: link
        force: yes

    - name: etc 用ディレクトリ作成
      file:
        path: ~/.etc
        state: directory
