[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntex'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown', 'mkd']
