[env]
# supports arbitrary env vars so mise can be used like direnv/dotenv

[tools]
# specify single or multiple versions
terraform = '1.6.6'
kubectl = '1.29.0'
kustomize = '5.3.0'
kind = 'latest'
fzf = 'latest'
ghq = 'latest'
gojq = 'latest'
bat = 'latest'
starship = 'latest'
awscli = 'latest'
aws-vault = 'latest'
github-cli = 'latest'
eza = 'latest'
delta = 'latest'

[plugins]
# specify a custom repo url
# note this will only be used if the plugin does not already exist

[alias.node] # project-local aliases
